[tropnis]
batch_size = 8192
evaluate_real_part = true
n_cores = 32
discrete_model = "transformer"
is_vacuum = true

[momtrop]
edge_weight = 0.555555555555

[transformer]
embedding_dim = 128
feedforward_dim = 256
heads = 8
mlp_units = 128
transformer_layers = 2

[parameterisation.layer_0]
param_type = "kaapo"

[parameterisation.layer_1]
param_type = "inverse spherical"
conformal_scale = 10.0

[parameterisation.layer_2]
param_type = "momtrop"

[integrand]
integrand_type = "kaapo"
