[gammaloop_state]
state_name = "physical_1L_6photons_output"
integration_state_name = "integration_physical_1L_6photons"
process_name = "physical_1L_6photons"

[tropnis]
batch_size = 8192
evaluate_real_part = true
n_cores = 32
discrete_model = "transformer"

[momtrop]
edge_weight = 0.555555555555

[transformer]
embedding_dim = 128
feedforward_dim = 256
heads = 8
mlp_units = 128
transformer_layers = 2

[parameterisation.layer_0]
param_type = "momtrop"

[integrand]
integrand_type = "gammaloop"
gammaloop_state_path =  "/shared/vhirshi/gammaloop_hedge_numerator/gl_states/physical_1L_6photons_output"
process_id = 0
integrand_name = "default"
use_f128 = false
momentum_space = true