[gammaloop_state]
state_name = "scalar_box_output"
integration_state_name = "integration_scalar_box"
process_name = "scalar_box"

[tropnis]
batch_size = 2048

[transformer]
embedding_dim = 64
feedforward_dim = 128
heads = 4
mlp_units = 64
transformer_layers = 2

[plotting_params.training_prog]
n_samples = 40000
n_samples_after_training = 100000