[gammaloop_state]
state_name = "physical_2L_6photons_output"
integration_state_name = "integration_physical_2L_6photons"
process_name = "physical_2L_6photons"

[tropnis]
batch_size = 16384
evaluate_real_part = true
n_cores = 32
discrete_model = "transformer"

[momtrop]
edge_weight = 0.5555555555

[transformer]
embedding_dim = 128
feedforward_dim = 256
heads = 8
mlp_units = 128
transformer_layers = 2
