[gammaloop_state]
state_name = "scalar_2_point_3_loop_output"
integration_state_name = "integration_scalar_2_point_3_loop"
process_name = "scalar_2_point_3_loop"

[tropnis]
batch_size = 4096
evaluate_real_part = false
n_cores = 32
discrete_model = "transformer"

[momtrop]
edge_weight = 0.78571428571

[transformer]
embedding_dim = 128
feedforward_dim = 256
heads = 8
mlp_units = 128
transformer_layers = 2