commands = [
    "import model scalars.json",
    "import graphs ./dot_files/scalar_6_point_2_loop.dot",
    "generate",
    "save dot ./gl_states/scalar_6_point_2_loop_output",
    "quit"
]

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics]
e_cm = 0.2

[default_runtime_settings.kinematics.externals.data]
momenta = [
    "dependent",
    [
        0.2,
        0.3,
        0.5,
        0.6
    ],
    [
        -0.1,
        0.7,
        0.2,
        0.1
    ],
    [
        0.1,
        0.5,
        -0.3,
        -0.4
    ],
    [
        -0.3,
        0.4,
        0.5,
        0.2
    ],
    [
        -0.2,
        0.3,
        0.2,
        -0.5
    ],
] 
helicities = [1, 1, 1, 1, 1, 1]

[default_runtime_settings.stability]
rotation_axis = []
check_on_norm = true

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[default_runtime_settings.sampling]
type = "default"
mode = "spherical"
mapping = "linear"

[cli_settings.global.generation]
enable_thresholds = false

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = true
compile = false

[default_runtime_settings.integrator]
seed = 42
n_increase = 100000
n_start = 100000
n_max = 10000000
discrete_dim_learning_rate = 1.5
continuous_dim_learning_rate = 1.5
max_prob_ratio = 0.01
