commands = [
    "import model scalars.json",
    "import graphs ./dot_files/scalar_3_point_1_loop.dot",
    "generate",
    "save dot ./gl_states/scalar_3_point_1_loop_output",
	"quit"
]

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics]
e_cm = 1.0

[default_runtime_settings.kinematics.externals.data]
momenta = [
    "dependent",
    [
        1.0,
        3.0,
        4.0,
        5.0,
    ],
    [
        -1.0,
        -6.0,
        -7.0,
        -8.0,
    ],
] 
helicities = [1, 1, 1]

[default_runtime_settings.stability]
rotation_axis = []
check_on_norm = true

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[default_runtime_settings.sampling]
type = "default"
mode = "spherical"
mapping = "linear"

[cli_settings.global.generation]
enable_thresholds = false

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = true
compile = false

[default_runtime_settings.integrator]
seed = 42
n_increase = 100000
n_start = 100000
n_max = 10000000
discrete_dim_learning_rate = 1.5
continuous_dim_learning_rate = 1.5
max_prob_ratio = 0.01
