commands = [
    "import model sm-default",
    "set model Gf=[1.19874983504616246e-5,0.]",
    "set model MZ=[91.188,0.]",
    "set model MT=[1500.,0.]",
    "set model ymt=[1500.,0.]",
    "set model aEWM1=[128.93,0.]",
    "import graphs ./dot_files/physical_1L_6photons.dot",
    "generate",
    "save dot ./gl_states/physical_1L_6photons_output",
    "quit"
]

[default_runtime_settings.general]
enable_cache = false

[default_runtime_settings.kinematics]
e_cm = 1.0

[default_runtime_settings.kinematics.externals]
type = "constant"

[default_runtime_settings.kinematics.externals.data]
momenta = [
    "dependent",
    [
        500.0,
        0.0,
        -300.0,
        400.0
    ],
    [
        500.0,
        0.0,
        300.0,
        -400.0
    ],
    [
        88.551333054502976,
        -22.100690287689979,
        40.080353191685333,
        -75.805430956936632
    ],
    [
        328.32941922709853,
        -103.84961188345630,
        -301.93375538954012,
        76.494921387165888
    ],
    [
        152.35810946743061,
        -105.88095966659220,
        -97.709638326975707,
        49.548385226792817
    ],
]
helicities = [
    -1,
    -1,
    -1,
    -1,
    -1,
    -1,
]

[default_runtime_settings.integrator]
n_increase = 0
n_start = 100000
n_max = 1000000
discrete_dim_learning_rate = 0.5
continuous_dim_learning_rate = 0.5

[default_runtime_settings.stability]
check_on_norm = true
rotation_axis = []


[[default_runtime_settings.stability.levels]]
precision = "Double"
required_precision_for_re = 0.00000001
required_precision_for_im = 0.00000001
escalate_for_large_weight_threshold = 0.9

[[default_runtime_settings.stability.levels]]
precision = "Quad"
required_precision_for_re = 0.00001
required_precision_for_im = 0.00001
escalate_for_large_weight_threshold = -1.0

[default_runtime_settings.subtraction]
disable_threshold_subtraction = true

[cli_settings.global.generation]
enable_thresholds = false

[cli_settings.global.generation.evaluator]
iterative_orientation_optimization = false
compile = false

[default_runtime_settings.sampling]
type = "default"
mode = "spherical"
mapping = "linear"
b = 10.0
